name: exo3

volumes:
  pgdata: {}   # volume Docker (persistant)

services:
  pg:
    image: postgres:latest
    container_name: exo3-pg
    env_file: ./.env          # POSTGRES_USER/DB/PASSWORD
    ports:
      - "127.0.0.1:5432:5432" # <-- uniquement localhost (optionnel)
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER:-john} -d ${POSTGRES_DB:-doe}"]
      interval: 5s
      timeout: 3s
      retries: 10
