FROM python:latest

# Définir le dossier de travail dans le conteneur
WORKDIR /app

# Copier ton script hello.py dans /app/
COPY hello.py .

# Commande par défaut au démarrage du conteneur
CMD ["python", "hello.py"]
